### ISSUE TITLE
elasticsearch数据源能链接但无法执行sql

### ISSUE THREAD

**Issue by datasophon** [openlookeng/hetu-core#421]
### Software Environment:
- OpenLooKeng version (source or binary):
1.9.0
- OS platform & distribution (eg., Linux Ubuntu 16.04):
centos7.9
- Java version:
### Describe the current behavior
1.8

### Describe the expected behavior
elasticsearch数据源能链接但无法执行sql

### Steps to reproduce the issue
1.配置elasticsearch数据源
2.查询elasticsearch数据
3.查询出现Name or service not known异常

### Related log/screenshots
_io.prestosql.spi.PrestoException: ddp5/172.29.67.142: Name or service not known
        at io.prestosql.elasticsearch.ElasticsearchClient.doRequest(ElasticsearchClient.java:578)
        at io.prestosql.elasticsearch.ElasticsearchClient.fetchNodes(ElasticsearchClient.java:340)
        at io.prestosql.elasticsearch.ElasticsearchClient.refreshNodes(ElasticsearchClient.java:164)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.UnknownHostException: ddp5/172.29.67.142: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:609)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:580)
        at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:427)
        at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:276)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:266)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:363)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:125)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
        at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:344)
        at org.elasticsearch.client.RestClient.access$600(RestClient.java:89)
        at org.elasticsearch.client.RestClient$1.retryIfPossible(RestClient.java:394)
        at org.elasticsearch.client.RestClient$1.failed(RestClient.java:376)
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:137)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalPoolEntryCallback.failed(PoolingNHttpClientConnectionMan_

### Special notes for this issue

**Comment by cbc666** [comment]
ddp5/172.29.67.142: Name or service not known
说明配置的地址不正确，可以去掉“ ddp5/” 试试
